import { getJson } from "./client";
import type { Description } from "./types";

export type { DescribeEntry, Description } from "./types";

/**
 * A rule's or a workflow's plain description (d19): generated by the API from
 * the stored config only, never by AI, so the editor, the CLI and the MCP
 * tools read the same lines from one vocabulary (culture_rules/model/describe.py).
 */
export function getDescription(
  noun: "rules" | "workflows",
  id: string,
  signal?: AbortSignal,
): Promise<Description> {
  return getJson<Description>(`/${noun}/${encodeURIComponent(id)}/describe`, signal);
}
